### ISSUE TITLE
Unclear how to connect/query administration within the container

### ISSUE THREAD

**Issue by recklessnl** [TeamSpeak-Systems/teamspeak-linux-docker-images#16]
There's barely any documentation on how to access the serveradmin account or query it within the docker environment - /bin/bash gives me the following error:

`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused"exec: \"bash\": executable file not found in $PATH"`

I have the following lines in my docker-compose file:

`      - TS3SERVER_QUERY_PROTOCOLS=ssh,raw
       - TS3SERVER_QUERY_SSH_RSA_HOST_KEY=mypassword`

When I try just regular /bin/sh and use `login serveradmin mypassword` it never lets me login. I read through the entire documentation of Teamspeak on Docker a couple of times and I really don't know how we're supposed to go inside the container and do administration. Any clarification would be great and would help other users in the future too I'd imagine.

**Comment by muenchow** [comment]
You access the query the same way as you would do with a regular teamspeak server. The only step you have to do before hand is publish the containers query port(s) in order to access it. After that you can access the query as usual. for example with `telnet localhost 10011`.

Under the section `How to use this image` in the [documentation](https://docs.docker.com/samples/library/teamspeak/), you will find an example that also shows how to publish port `10011`.
Should you want ot use ssh instead of telnet, you must publish `10022`
